namespace: community
name: general
version: 1.0.0
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: null
license_file: COPYING
tags: null
# NOTE: No more dependencies can be added to this list
dependencies:
  ansible.netcommon: '>=1.0.0'
  ansible.posix: '>=1.0.0'
  community.kubernetes: '>=0.11.1'  # check https://galaxy.ansible.com/community/kubernetes
  google.cloud: '>=0.10.1'  # check https://galaxy.ansible.com/google/cloud
repository: https://github.com/ansible-collections/community.general
#documentation: https://github.com/ansible-collection-migration/community.general/tree/main/docs
homepage: https://github.com/ansible-collections/community.general
issues: https://github.com/ansible-collections/community.general/issues
#type: flatmap
