name: Bug Report
about: Create a report to help us improve

body:

  - type: markdown
    attributes:
      value: |
        Verify first that your issue is not already reported on [GitHub](https://github.com/ansible-collections/community.general/issues)
        Also test if the latest release and main branch are affected too

  - type: textarea
    attributes:
      label: Summary
      description: 'Explain the problem briefly below'
    validations:
      required: true

  - type: dropdown
    attributes:
      # FIXME: Once GitHub allows defining the default choice, update this
      label: Issue Type
      options:
        - Bug Report
    validations:
      required: true

  - type: textarea
    attributes:
      # For smaller collections we could use a multi-select and hardcode the list
      # May generate this list via GitHub action and walking files under https://github.com/ansible-collections/community.general/tree/main/plugins
      # Select from list, filter as you type (`mysql` would only show the 3 mysql components)
      # OR freeform - doesn't seem to be supported in adaptivecards

      label: Component Name
      description: 'List the component, ie `template`, `mysql_users`'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Ansible Version
      description: |
        Paste verbatim output from `ansible --version` between quotes
      value: |
         ```paste below

         ```
  - type: textarea
    attributes:
      label: Configuration
      description: |
        If this issue has an example piece of YAML that can help to reproduce this problem, please provide it.
        This can be a piece of YAML from, e.g., an automation, script, scene or configuration.
        Paste verbatim output from `ansible-config dump --only-changed` between quotes
      value: |
         ```paste below

         ```
  - type: textarea
    attributes:
      label: OS / Environment
      description: 'Provide all relevant information below, e.g. target OS versions, network device firmware, etc'

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: 'Describe exactly how to reproduce the problem, using a minimal test-case'
      value: |
         ```paste below

         ```
  - type: textarea
    attributes:
      label: Expected Results
      description: |
        Describe what you expected to happen when running the steps above

  - type: textarea
    attributes:
      label: Actual Results
      description: 'Describe what actually happened. If possible run with extra verbosity (`ansible-playbook -vvvv`)'
      value: |
         ```paste below

         ```
