---
<<<<<<< HEAD
name: 📝 Documentation Report
description: Ask us about docs
=======
name: Documentation Report
description: Ask us about docs
# NOTE: issue body is enabled to allow screenshots
issue_body: true  # default: true, adds a classic WSYWIG textarea, if on
>>>>>>> f49cf2c22d (Add other GH Issue forms (#1968))

body:
- type: markdown
  attributes:
<<<<<<< HEAD
    value: >
      **Thank you for wanting to report a problem with ansible-core
      documentation!**


      Please fill out your suggestions below. If the problem seems
      straightforward, feel free to go ahead and
      [submit a pull request] instead!


      ⚠
      Verify first that your issue is not [already reported on
      GitHub][issue search].

      Also test if the latest release and devel branch are affected too.


      **Tip:** If you are seeking community support, please consider
      [starting a mailing list thread or chatting in IRC][ML||IRC].


      [ML||IRC]:
      https://docs.ansible.com/ansible-core/devel/community/communication.html?utm_medium=github&utm_source=issue_form--documentation_report.yml#mailing-list-information

      [issue search]: ../search?q=is%3Aissue&type=issues

      [submit a pull request]:
      https://docs.ansible.com/ansible-core/devel/community/documentation_contributions.html
=======
    value: |
      ⚠
      Verify first that your issue is not [already reported on GitHub][issue search].
      Also test if the latest release and devel branch are affected too.
      *Complete **all** sections as described, this form is processed automatically.*

      [issue search]: https://github.com/ansible-collections/community.general/search?q=is%3Aissue&type=issues
>>>>>>> f49cf2c22d (Add other GH Issue forms (#1968))


- type: textarea
  attributes:
    label: Summary
<<<<<<< HEAD
    description: >
      Explain the problem briefly below, add suggestions to wording
      or structure.


      **HINT:** Did you know the documentation has a `View on GitHub`
      link on some pages? Feel free to use it to start a pull request
      right from the GitHub UI!
    placeholder: >-
      I was reading the ansible-core documentation of version X and I'm having
=======
    description: |
      Explain the problem briefly below, add suggestions to wording or structure.

      **HINT:** Did you know the documentation has an `Edit on GitHub` link on every page?
    placeholder: >-
      I was reading the Collection documentation of version X and I'm having
>>>>>>> f49cf2c22d (Add other GH Issue forms (#1968))
      problems understanding Y. It would be very helpful if that got
      rephrased as Z.
  validations:
    required: true

- type: dropdown
  attributes:
    label: Issue Type
<<<<<<< HEAD
    description: >
      Please select the single available option in the drop-down.

      <details>
        <summary>
          <em>Why?</em>
        </summary>

        We would do it by ourselves but unfortunatelly, the curent
        edition of GitHub Issue Forms Alpha does not support this yet 🤷


        _We will make it easier in the future, once GitHub
        supports dropdown defaults. Promise!_

      </details>
=======
>>>>>>> f49cf2c22d (Add other GH Issue forms (#1968))
    # FIXME: Once GitHub allows defining the default choice, update this
    options:
    - Documentation Report
  validations:
    required: true

- type: input
  attributes:
    label: Component Name
<<<<<<< HEAD
    description: >
      Write the short name of the rst file, module, plugin, task or
      feature below, *use your best guess if unsure*.


      **Tip:** Be advised that the source for some parts of the
      documentation are hosted outside of this repository. If the page
      you are reporting describes modules/plugins/etc that are not
      officially supported by the Ansible Core Engineering team, there
      is a good chance that it is coming from one of the [Ansible
      Collections maintained by the community][collections org]. If this
      is the case, please make sure to file an issue under the
      appropriate project there instead.


      [collections org]: /ansible-collections
    placeholder: docs/docsite/rst/dev_guide/debugging.rst
=======
    description: >-
      Write the short name of the rst file, module, plugin, task or
      feature below, *use your best guess if unsure*.
    placeholder: mysql_user
>>>>>>> f49cf2c22d (Add other GH Issue forms (#1968))
  validations:
    required: true

- type: textarea
  attributes:
    label: Ansible Version
    description: >-
<<<<<<< HEAD
      Paste verbatim output from `ansible --version` below, under
      the prompt line. Please don't wrap it with tripple backticks — your
      whole input will be turned into a code snippet automatically.
    render: console
    value: |
      $ ansible --version
    placeholder: |
      $ ansible --version
      ansible [core 2.11.0b4.post0]  (detached HEAD ref: refs/) last updated 2021/04/02 00:33:35 (GMT +200)
        config file = None
        configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
        ansible python module location = ~/src/github/ansible/ansible/lib/ansible
        ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
        executable location = bin/ansible
        python version = 3.9.0 (default, Oct 26 2020, 13:08:59) [GCC 10.2.0]
        jinja version = 2.11.3
        libyaml = True
  validations:
    required: true
=======
      Paste verbatim output from `ansible --version` between
      tripple backticks.
    value: |
      ```console (paste below)
      $ ansible --version

      ```
  validations:
    required: false
>>>>>>> f49cf2c22d (Add other GH Issue forms (#1968))

- type: textarea
  attributes:
    label: Configuration
    description: >-
<<<<<<< HEAD
      Paste verbatim output from `ansible-config dump --only-changed -t all` below, under the prompt line.
      (if using a version older than ansible-core 2.12 you should omit the '-t all')
      Please don't wrap it with tripple backticks — your
      whole input will be turned into a code snippet automatically.
    render: console
    value: |
      # if using a version older than ansible-core 2.12 you should omit the '-t all'
      $ ansible-config dump --only-changed -t all
    placeholder: |
      # if using a version older than ansible-core 2.12 you should omit the '-t all'
      $ ansible-config dump --only-changed -t all
      DEFAULT_GATHERING(~/src/github/ansible/ansible/ansible.cfg) = smart
      DEFAULT_HOST_LIST(~/src/github/ansible/ansible/ansible.cfg) = ['~/src/github/ansible/ansible/hosts']
      DEFAULT_VAULT_PASSWORD_FILE(~/src/github/ansible/ansible/ansible.cfg) = ~/src/github/ansible/ansible/vault/print-password.sh
  validations:
    required: true
=======
      Paste verbatim output from `ansible-config dump --only-changed` between quotes.
    value: |
      ```console (paste below)
      $ ansible-config dump --only-changed

      ```
  validations:
    required: false
>>>>>>> f49cf2c22d (Add other GH Issue forms (#1968))

- type: textarea
  attributes:
    label: OS / Environment
    description: >-
      Provide all relevant information below, e.g. OS version,
      browser, etc.
    placeholder: Fedora 33, Firefox etc.
  validations:
<<<<<<< HEAD
    required: true

=======
    required: false
>>>>>>> f49cf2c22d (Add other GH Issue forms (#1968))

- type: textarea
  attributes:
    label: Additional Information
    description: |
      Describe how this improves the documentation, e.g. before/after situation or screenshots.

<<<<<<< HEAD
=======
      **Tip:** It's not possible to upload the screenshot via this field directly but you can use the last textarea in this form to attach them.

>>>>>>> f49cf2c22d (Add other GH Issue forms (#1968))
      **HINT:** You can paste https://gist.github.com links for larger files.
    placeholder: >-
      When the improvement is applied, it makes it more straightforward
      to understand X.
  validations:
<<<<<<< HEAD
    required: true


- type: markdown
  attributes:
    value: >
      *One last thing...*


      *Please, complete **all** sections as described, this form
      is [processed automatically by a robot][ansibot help].*


      Thank you for your collaboration!


      [ansibot help]:
      /ansible/ansibullbot/blob/master/ISSUE_HELP.md#for-issue-submitters

=======
    required: false
>>>>>>> f49cf2c22d (Add other GH Issue forms (#1968))

- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [Ansible Code of Conduct][CoC] first.
<<<<<<< HEAD

      [CoC]: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html?utm_medium=github&utm_source=issue_form--documentation_report.yml
=======
      [CoC]: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html?utm_medium=github&utm_source=issue_form--ansible-collections
>>>>>>> f49cf2c22d (Add other GH Issue forms (#1968))
    options:
    - label: I agree to follow the Ansible Code of Conduct
      required: true
...
