bugfixes:
  - kdeconfig - ``kwriteconfig`` executable could not be discovered automatically on systems with only ``kwriteconfig6`` installed.
    ``kwriteconfig6`` can now be discovered by Ansible (https://github.com/ansible-collections/community.general/pull/10751).