---
minor_changes:
  - nmcli - add infiniband type support (https://github.com/ansible-collections/community.general/pull/1260).
  - nmcli - add ``ipv4.routes``,  ``ipv4.route-metric`` and ``ipv4.never-default`` support (https://github.com/ansible-collections/community.general/pull/1260).
