---
minor_changes:
  - git_config - when the existing values have spaces, the step will report as changed only if the content changed (https://github.com/ansible-collections/community.general/pull/2028).
