minor_changes:
  - Add support new fields in ipa_config module for ipadefaultprimarygroup, ipagroupsearchfields, ipahomesrootdir, ipamaxusernamelength, ipapwdexpadvnotify, ipasearchrecordslimit, ipasearchtimelimit, ipauserauthtype, and ipausersearchfields.  (https://github.com/ansible-collections/community.general/pull/2116)
