bugfixes:
  - git_config - fixed scope ``file`` behaviour, added integraton test for it, marked integration tests as destructive (https://github.com/ansible-collections/community.general/issues/2117).
