bugfixes:
  - "nmcli - added ip4/ip6 configuration arguments for ``sit`` tunnels (https://github.com/ansible-collections/community.general/issues/3238, https://github.com/ansible-collections/community.general/pull/3239)."
