bugfixes:
    - redfish_utils - add workaround to ``SetBiosAttributes`` for systems with firmware from AMI that do not properly implement ``@Redfish.Settings`` (https://github.com/ansible-collections/community.general/issues/6433).
