# (C) 2025 Alexei Znamensky
# Licensed under the MIT License. See LICENSES/MIT.txt for details.
# SPDX-FileCopyrightText: 2025 Alexei Znamensky
# SPDX-License-Identifier: MIT

FROM mcr.microsoft.com/devcontainers/python:3.14-bookworm

WORKDIR /workspace/ansible_collections/community/general

RUN chown -R vscode:vscode /workspace/. \
    && pip install -U pip
