---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

trigger:
  batch: true
  branches:
    include:
      - main
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - main
      - stable-*

schedules:
  - cron: 0 8 * * *
    displayName: Nightly (main)
    always: true
    branches:
      include:
        - main
  - cron: 0 10 * * *
    displayName: Nightly (active stable branches)
    always: true
    branches:
      include:
        - stable-13
        - stable-12
  - cron: 0 11 * * 0
    displayName: Weekly (old stable branches)
    always: true
    branches:
      include:
        - stable-11

variables:
  - name: checkoutPath
    value: ansible_collections/community/general
  - name: coverageBranches
    value: main
  - name: entryPoint
    value: tests/utils/shippable/nox.sh
  - name: prepareEntryPoint
    value: tests/utils/shippable/nox-prepare.sh
  - name: fetchDepth
    value: 0

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:8.0.0

pool: Standard

stages:
  - stage: remote_devel
    displayName: Remote devel
    dependsOn: []
    variables:
      entryPoint: tests/utils/shippable/nox.sh
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: FreeBSD 14.4 + group 1
              test: ansible-test-integration-devel-freebsd-14.4-azp-posix-1
            - name: FreeBSD 14.4 + group 2
              test: ansible-test-integration-devel-freebsd-14.4-azp-posix-2
            - name: FreeBSD 14.4 + group 3
              test: ansible-test-integration-devel-freebsd-14.4-azp-posix-3
            - name: FreeBSD 15.0 + group 1
              test: ansible-test-integration-devel-freebsd-15.0-azp-posix-1
            - name: FreeBSD 15.0 + group 2
              test: ansible-test-integration-devel-freebsd-15.0-azp-posix-2
            - name: FreeBSD 15.0 + group 3
              test: ansible-test-integration-devel-freebsd-15.0-azp-posix-3

  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - remote_devel
    jobs:
      - template: templates/coverage.yml
