---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

name: nox
'on':
  push:
    branches:
      - main
      - stable-*
    paths:
      - docs/**
      - .github/workflows/docs.yml
  pull_request:
    paths:
      - docs/**
      - .github/workflows/docs.yml
  # Run CI once per day (at 08:00 UTC)
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  nox:
    uses: ansible-community/antsibull-nox/.github/workflows/reusable-nox-run.yml@main
    with:
      session-name: Run extra sanity tests
      sessions: ansible-output
